// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'AkarIcons:facebookFill': typeof import('~icons/akar-icons/facebook-fill')['default']
    'AkarIcons:twitterFill': typeof import('~icons/akar-icons/twitter-fill')['default']
    'AntDesign:mailOutlined': typeof import('~icons/ant-design/mail-outlined')['default']
    'Brandico:facebook': typeof import('~icons/brandico/facebook')['default']
    'Bxl:facebook': typeof import('~icons/bx/l-facebook')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Card: typeof import('./components/Card.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    README: typeof import('./components/README.md')['default']
    ResearchCard: typeof import('./components/ResearchCard.vue')['default']
  }
}

export { }
